name: Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    timeout-minutes: 1

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install
      run: |
        npm install --legacy-peer-deps

    - name: Build
      run: |
        npx webpack

    - name: Instalar lftp
      run: |
        sudo apt-get update
        sudo apt-get install lftp

    - name: Upload to Hostinger via FTP
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        echo "mirror -e -R dist public_html" > ftp_commands
        lftp -u $FTP_USERNAME,$FTP_PASSWORD ftp://greenlashgames.com -e "set ftp:ssl-allow off; source ftp_commands" 

