name: Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    timeout-minutes: 1

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install
      run: |
        npm install --legacy-peer-deps

    - name: Build
      run: |
        npx webpack

    - name: Instalar lftp
      run: |
        sudo apt-get update
        sudo apt-get install lftp

    - name: Upload to Hostinger via FTP
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        echo -e "open -u $FTP_USERNAME,$FTP_PASSWORD -p21 greenlashgames.com" > lftp_commands
        echo -e "mirror -R dist" >> lftp_commands
        echo -e "set ftp:ssl-allow no" >> lftp_commands
        echo -e "set ftp:use-feat no" >> lftp_commands
        echo -e "set net:reconnect-interval-base 5" >> lftp_commands
        echo -e "set net:max-retries 2" >> lftp_commands
        echo -e "set net:reconnect-interval-multiplier 1" >> lftp_commands
        echo -e "set net:reconnect-interval-max 60" >> lftp_commands
        echo -e "set net:timeout 9999" >> lftp_commands
        echo -e "set net:max-retries 1" >> lftp_commands

        # Ejecutar la transferencia FTP
        lftp -f lftp_commands

